# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # multi-machine docs: https://www.vagrantup.com/docs/multi-machine

  INSTALL_BINARY = <<-SHELL
    # todo
  SHELL

  # we could have custom boxes per defined VM, just using ubuntu/focal64 for stability for widespread use.
  config.vm.box = "ubuntu/focal64"

  config.vm.define "binary" do |binary|
    binary.vm.network "private_network", ip: "192.168.20.10"
    binary.vm.provision "shell", inline: $INSTALL_BINARY
  end 

  # install with get.docker.com 
    # via vagrant shell provisioner to stream line the install and not need even an inline script
  config.vm.define "gety" do |gety|
    gety.vm.network "private_network", ip: "192.168.20.12"
    gety.vm.provision "shell", path: "https://get.docker.com"
  end 

  # use snap to install docker
  config.vm.define "snappy" do |snappy|
    snappy.vm.network "private_network", ip: "192.168.20.14"
    snappy.vm.provision "shell", inline: $SNAPPY_INSTALL
  end

  # use snap to install docker
  config.vm.define "ansibles" do |ansibles|
    ansibles.vm.network "private_network", ip: "192.168.20.16"
    #snappy.vm.provision "ansible_local", playbook: ""
  end

  SNAPPY_INSTALL = <<-SHELL

  SHELL

  # ANSIBLE DOCKER route too?
  # https://github.com/thomvaill/tads-boilerplate/blob/master/ansible/provision-01-docker.yml
  # https://github.com/geerlingguy/ansible-role-docker

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = "8192"
  end

end
