
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "getdc"

  config.vm.network "private_network", ip: "192.168.30.101"

  config.vm.provision "shell", path: "config.learn.ubuntu.sh", name: "learns"
  config.vm.provision "shell", path: "https://get.docker.com", name: "dockers"
  config.vm.provision "shell", path: "config.docker.after.install.sh", name: "afters"
  
end
