Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "getdc"

  # provisioners (break apart advantage - as you deveop the script you can test slices easily)
  config.vm.provision "shell", path: "config.learn.ubuntu.sh", name: "learns"
  config.vm.provision "shell", path: "https://get.docker.com", name: "dockers"
  config.vm.provision "shell", path: "config.docker.after.install.sh", name: "afters"
  # options: https://www.vagrantup.com/docs/provisioning/shell#options
  # consider docker config files via file provisioner - I don't like the coupling to vagrant but it may be nice and explicit
    # config.vm.provision "file"
    
  config.vm.network "private_network", ip: "192.168.30.101"

end
