Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "cli-only"

  # https://www.vagrantup.com/docs/provisioning/ansible_local
  # todo see docs and watch for changes coming to support ansible's new collections feature, you can always install those with a shell script provisioner if necessary in advance of running your playbook
  config.vm.provision "ansible_local" do |ansible|
    ansible.become = true
    ansible.install_mode = "pip" # uses pip to install ansible, so vagrant first tries to install pip, then ansible via pip
    ansible.playbook = "playbook.yml"
  end

  config.vm.network "private_network", ip: "192.168.30.102"

end
