Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "cli-only"

  config.vm.provision "shell", path: "ensure.ansible.sh"

  # https://www.vagrantup.com/docs/provisioning/ansible_local
  config.vm.provision "ansible_local" do |ansible|
    ansible.become = true
    # since ansible is already installed, this provisioner only deals with running my playbook
    ansible.playbook = "client-only.yml"
    # ansible.verbose = "vvv" # true/"v" "vvv" "vvvv"
  end

  config.vm.network "private_network", ip: "192.168.30.102"

end
