
# arch tends to keep up to date with upstreams and goal is minimal mods to upstream builds

Vagrant.configure("2") do |config|
  
  config.vm.box = "generic/arch"
  config.vm.hostname = "archy"


  # docker package: https://archlinux.org/packages/community/x86_64/docker/
  config.vm.provision "shell", inline: <<-SHELL
    
  SHELL

  config.vm.network "private_network", ip: "192.168.30.105"

end
