Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "rootless"

  config.vm.network "private_network", ip: "192.168.30.110"

  config.vm.provision "shell", path: "config.learn.ubuntu.sh", name: "learns"
  config.vm.provision "shell", path: "https://get.docker.com", name: "dockers"
  
end

## Notes
# - Also, test build's conveience script: https://test.docker.com 
# - Question: shell provisioner taking in the script directly couples the example to vagrant, how do you feel about that? 
