Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/focal64'
  config.vm.hostname = 'alone-pkg'
  config.vm.network 'private_network', ip: '192.168.30.121'
  config.vm.provision 'shell', path: 'containerd.from.package.sh'
end
