Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/focal64'
  config.vm.hostname = 'snappy'
  config.vm.network 'private_network', ip: '192.168.30.103'

  config.vm.provision 'shell', inline: <<-SHELL
    sudo addgroup --system docker
    sudo adduser vagrant docker
  SHELL 

  config.vm.provision "shell", inline: <<-SHELL
    sudo snap refresh
    sudo snap install docker
  SHELL
  
end
