Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/focal64'
  config.vm.hostname = 'secured'
  config.vm.network 'private_network', ip: '192.168.30.110'
  config.vm.provision 'shell', path: 'install.from.binaries.sh'
  config.vm.provision 'shell', path: 'install.mkcert.sh'
end
