Vagrant.configure('2') do |config|
  config.vm.box = 'generic/ubuntu2004'
  config.vm.hostname = 'binaries'
  config.vm.network 'private_network', ip: '192.168.30.109'
  config.vm.provision 'shell', path: 'install.from.binaries.sh'
end
