Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/focal64'
  config.vm.hostname = 'alone'
  config.vm.network 'private_network', ip: '192.168.30.120'
  config.vm.provision 'shell', path: 'containerd.from.github.sh'
  config.vm.provision 'shell', path: 'scripts/runc.from.github.sh'
end
