Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/focal64'
  config.vm.provision 'shell', path: 'scripts/1-config.learn.ubuntu.sh'
  config.vm.provision 'shell', path: 'https://get.docker.com'
  config.vm.provision 'shell', path: 'scripts/3-config.docker.after.install.sh'

  # define manager(s)
  (1..3).each do |num|
    config.vm.define "m#{num}" do |manager|
      manager.vm.hostname = "m#{num}"
      manager.vm.network 'private_network', ip: "192.168.30.13#{num}"
    end
  end

  # define worker(s)
  (1..3).each do |num|
    config.vm.define "w#{num}" do |worker|
      worker.vm.hostname = "w#{num}"
      worker.vm.network 'private_network', ip: "192.168.30.14#{num}"
    end
  end

  # CAUTION: this is per VM! adjust as necessary for your hardware
  # decrease the number of VMs with the loop counter if need be
  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = 2
    vb.memory = '4096'
  end
end
