Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/focal64'
  config.vm.hostname = 'microk8s'

  config.vm.network 'private_network', ip: '192.168.30.201'

  config.vm.provision 'shell', path: 'config.learn.ubuntu.sh', name: 'learns'
  config.vm.provision 'shell', path: 'install.snap.sh', name: 'install'
  config.vm.provision 'shell', path: 'post-install.sh', name: 'post-install'
end
